---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: dp-behandling-alerts
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  groups:
    - name: dp-behandling-flyt
      rules:
        - alert: FlytAvvik
          expr: |
            abs(
              avg_over_time((sum(rate(dp_behandling_status_total[1h] offset 1w)) by (status)*60*60)[3h:]) 
              - (
                avg_over_time((sum(rate(dp_behandling_status_total[1h] offset 1w)) by (status) * 60 * 60) [3h:]) + 
                avg_over_time((sum(rate(dp_behandling_status_total[1h] offset 2w)) by (status) * 60 * 60) [3h:]) + 
                avg_over_time((sum(rate(dp_behandling_status_total[1h] offset 3w)) by (status) * 60 * 60) [3h:])
                ) / 3
            ) > 5
          for: 5m
          annotations:
            consequence: 'For stort avvik fra trend siste 3 uker for behandlingsstatus *{{ $labels.status }}*'
          labels:
            namespace: teamdagpenger
            severity: warning