apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-vedtak
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: {{ image }}
  port: 8080
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      memory: 512Mi
    requests:
      memory: 256Mi
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true
  gcp:
    sqlInstances:
      - type: POSTGRES_15
        highAvailability: true
        diskAutoresize: true
        pointInTimeRecovery: true
        tier: {{gcp.sql.tier}}
        databases:
          - name: vedtak
            envVarPrefix: DB
  kafka:
    pool: {{ kafka_pool }}
  env:
    - name: flyway.cleanDisabled
      value: {{ flyway.cleanDisabled }}

