apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-behandling
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: "{{ image }}"
  port: 8080
  strategy:
    type: Recreate # Bruk kun Recreate når vi deployer store/ukompatible migreringer
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 2
    max: 2
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 384Mi
  env:
    - name: JDK_JAVA_OPTIONS
      value: -XX:+UseParallelGC -XX:MaxRAMPercentage=35.0 -XX:ActiveProcessorCount=4
    - name: GRUPPER_SAKSBEHANDLER
      value: {{azure.grupper.saksbehandler}}
    - name: KAFKA_EXTRA_TOPIC
      value: {{kafka.extra_topic}}
    # Avbryt innvilgelse etter x dager. Dette trenger vi en overgangsperiode med Arena
    - name: AVBRYT_INNVILGELSE_ETTER_DAGER
      value: "{{avbryt_innvilgelse_etter_dager}}"
  envFrom:
    - secret: dp-behandling-unleash-api-token
  {{#if ingresses}}
  ingresses:
    {{#each ingresses as |url|}}
     - {{url}}
    {{/each}}
  {{/if}}
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true
      tenant: {{azure.tenant}}
      claims:
        extra:
          - NAVident
        groups:
          - id: {{azure.grupper.saksbehandler}}
          - id: {{azure.grupper.beslutter}}
  observability:
    logging:
      destinations:
        - id: loki
        - id: elastic
    autoInstrumentation:
      enabled: true
      runtime: java
  gcp:
    sqlInstances:
      - type: POSTGRES_15
        highAvailability: true
        diskAutoresize: true
        pointInTimeRecovery: true
        tier: {{gcp.sql.tier}}
        databases:
          - name: behandling
            envVarPrefix: DB
  kafka:
    pool: "{{ kafka.pool }}"
  accessPolicy:
    outbound:
      external:
        - host: teamdagpenger-unleash-api.nav.cloud.nais.io
    inbound:
      rules:
        - application: dp-saksbehandling-frontend
        - application: dp-saksbehandling
        - application: dp-melding-om-vedtak
        {{#if wonderwalled}}
        - application: wonderwalled-idporten
          namespace: aura
        - application: wonderwalled-azure
          namespace: aura
        - application: azure-token-generator
          namespace: aura
        {{/if}}

