name: AsyncAPI documents processing

on:
  push:
    branches:
      - main
    paths:
      - docs/api/async-api.yaml
      - .github/workflows/async-api.yaml

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generating HTML from AsyncAPI file
        run: |
          npx @asyncapi/generator docs/api/async-api.yaml @asyncapi/html-template -o docs

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs