name: AsyncAPI documents processing

on:
  push:
    branches:
      - feature/asyncapi
    paths:
      - docs/api/async-api.yaml
      - .github/workflows/async-api.yaml

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      #"standard step" where repo needs to be checked-out first
      - name: Checkout repo
        uses: actions/checkout@v3

      #In case you do not want to use defaults, you for example want to use different template
      - name: Generating HTML from my AsyncAPI document
        uses: docker://asyncapi/github-action-for-generator:2.0.0
        with:
          filepath: docs/api/async-api.yml
