name: Database diagram

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: [ "mediator/src/main/resources/db/migration/**" ]

permissions:
  contents: write

jobs:
  diagram:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: navikt/flyway2mermaid@v1
        with:
          migrations: mediator/src/main/resources/db/migration/
