name: Docs to PDF

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**.md'
      - 'docs/images/**'
      - '.github/workflows/docs-as-pdf.yml'

jobs:
  converttopdf:
    name: Bygg PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: baileyjm02/markdown-to-pdf@v2
        with:
          input_path: docs
          output_dir: pdfs
          images_dir: docs/images
          # for example <img src="./images/file-name.png">
          image_import: ./images
          # Default is true, can set to false to only get PDF files
          build_html: false
      - uses: actions/upload-artifact@v4
        with:
          name: docs
          path: pdfs